name: Unit Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  BUILD_TYPE: Release
  RAM_DISK: /mnt/ramdisk

jobs:
  unit_test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10

    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4

    - name: Install required packages
      shell: bash
      run: >
        sudo apt update && sudo apt install -y
        libpmemobj-dev

    - name: Create Build Environment
      shell: bash
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        sudo mkdir ${RAM_DISK}
        sudo mount -t tmpfs -o size=512m /dev/shm ${RAM_DISK}
        sudo chmod 777 ${RAM_DISK}

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ${GITHUB_WORKSPACE}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DPMEM_MANAGER_BUILD_TESTS=ON
        -DDBGROUP_TEST_TMP_PMEM_PATH=${RAM_DISK}

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
